version: '2'

services:
  web:
    image: nginx:1.15.0
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes: 
      - ./src:/src
      - ./web/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build: ./app
    env_file: .env
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
    volumes:
      - ./app/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./src:/src
  
  db:
    build: ./db
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
      
volumes:
  db-data:
